language: node_js
node_js:
    - "5"

# services:
#    - docker

addons:
  apt:
    sources:
    packages:
#      - shellcheck

before_install:
    - echo "deb http://archive.ubuntu.com/ubuntu/ wily universe" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
    - sudo apt-get install -y shellcheck
#    - docker build -t tnpi/mt6:latest .
#    - docker run -d --name mt6 tnpi/mt6:latest /

install:
    - test -f mail-toaster.sh

before_script:
#  - sudo curl -Lso \
#      /usr/bin/shellcheck \
#          https://github.com/caarlos0/shellcheck-docker/releases/download/v0.4.3/shellcheck
#  - sudo chmod +x /usr/bin/shellcheck

script:
   - sh -n *.sh
   - shellcheck -e SC2009,SC2086,SC2153,SC2016,SC1004,SC2119 *.sh

# after_success:
# after_failure:
after_script:

# required until the apt addon shellcheck is available
sudo: required
dist: trusty
